feat: support for the bun package manger
sapphiredev/documentation-plugins pull request #187
Opened 2023-09-12 21:24 UTC by y-71

I wanted to add bun as a package manager on your repo,

In order to not break the internet, i didn't want to rename the `npm2yarn2pnpm` folder before speaking to a maintainer.

looking forward to hear what you think

2023-09-12 22:04 UTC, favna requested changes

2023-09-12 22:04 UTC, favna commented on packages/npm2yarn2pnpm/src/npm2bun.ts
> +/**
Remove this copyright license header. By contributing to sapphire you accept that your code falls under the Sapphire MIT license.

Alternatively if you reject this way of handling licensed code (which might I add is totally normal for basically any half serious or higher GitHub org) then the only other option is to close your PR but be wary that someone else might eventually come around and implement the same code because it really isn't all that special, especially because it's essentially a copy of npm2yarn and npm2pnpm.

2023-09-12 22:04 UTC, favna commented on packages/npm2yarn2pnpm/src/npm2bun.ts
Make sure this function is exported through index.ts like the others also are.

2023-09-12 22:06 UTC, favna commented
We won't be changing the package name. That's throwing away all the goodwill, analytics, userbase, and more that the current package has gained. It's extremely destructive and extremely stupid. As stated in the review comments, please add a plugin option that defaults to false named `convertToBun` and add proper TSDoc on the comment.

2023-09-15 10:50 UTC, y-71 commented
@favna just in case you missed it, i've requested a review

2023-09-15 19:00 UTC, favna commented
Don't worry I'll get to this in the weekend. Work days are busy due to work.

2023-09-16 11:44 UTC, favna approved these changes

2023-09-16 11:45 UTC, merged

2023-09-16 11:53 UTC, favna commented
Released `@sapphire/docusaurus-plugin-npm2yarn2pnpm@1.2.0`